### ISSUE TITLE
Bump target-lexicon once target-lexicon#25 is fixed

### ISSUE THREAD

**Issue by stefson** [CraneStation/cranelift#977]
full build log: 

```
cargo build -j 2
    Updating crates.io index
  Downloaded capstone v0.6.0
  Downloaded file-per-thread-logger v0.1.2
  Downloaded term v0.6.1
  Downloaded failure_derive v0.1.5
  Downloaded memmap v0.7.0
  Downloaded filecheck v0.4.0
  Downloaded clap v2.33.0
  Downloaded cfg-if v0.1.9
  Downloaded indicatif v0.11.0
  Downloaded libc v0.2.62
  Downloaded num_cpus v1.10.1
  Downloaded wasmparser v0.37.1
  Downloaded failure v0.1.5
  Downloaded walkdir v2.2.9
  Downloaded log v0.4.8
  Downloaded serde v1.0.99
  Downloaded wabt v0.9.1
  Downloaded errno v0.2.4
  Downloaded faerie v0.11.0
  Downloaded target-lexicon v0.8.0
  Downloaded goblin v0.0.24
  Downloaded region v2.1.2
  Downloaded atty v0.2.13
  Downloaded capstone-sys v0.10.0
  Downloaded proc-macro2 v0.4.30
  Downloaded backtrace v0.3.37
  Downloaded string-interner v0.7.1
  Downloaded scroll v0.9.2
  Downloaded serde_json v1.0.40
  Downloaded wabt-sys v0.6.1
  Downloaded quote v0.6.13
  Downloaded unicode-width v0.1.6
  Downloaded env_logger v0.6.2
  Downloaded regex v1.3.1
  Downloaded ansi_term v0.11.0
  Downloaded bitflags v1.1.0
  Downloaded console v0.8.0
  Downloaded lazy_static v1.4.0
  Downloaded strsim v0.8.0
  Downloaded vec_map v0.8.1
  Downloaded dirs v2.0.2
  Downloaded syn v0.15.44
  Downloaded pretty_env_logger v0.3.1
  Downloaded number_prefix v0.2.8
  Downloaded parking_lot v0.9.0
  Downloaded serde_derive v1.0.99
  Downloaded synstructure v0.10.2
  Downloaded same-file v1.0.5
  Downloaded cc v1.0.41
  Downloaded indexmap v1.1.0
  Downloaded rustc_version v0.2.3
  Downloaded plain v0.2.3
  Downloaded thread_local v0.3.6
  Downloaded termios v0.3.1
  Downloaded proc-macro2 v1.0.2
  Downloaded syn v1.0.5
  Downloaded itoa v0.4.4
  Downloaded termcolor v1.0.5
  Downloaded clicolors-control v1.0.1
  Downloaded num-traits v0.2.8
  Downloaded textwrap v0.11.0
  Downloaded rustc-demangle v0.1.16
  Downloaded memchr v2.2.1
  Downloaded lock_api v0.3.1
  Downloaded humantime v1.2.0
  Downloaded backtrace-sys v0.1.31
  Downloaded chrono v0.4.9
  Downloaded quote v1.0.2
  Downloaded cmake v0.1.42
  Downloaded regex-syntax v0.6.12
  Downloaded unicode-xid v0.1.0
  Downloaded parking_lot_core v0.6.2
  Downloaded scroll_derive v0.9.5
  Downloaded dirs-sys v0.3.4
  Downloaded aho-corasick v0.7.6
  Downloaded autocfg v0.1.6
  Downloaded time v0.1.42
  Downloaded scopeguard v1.0.0
  Downloaded unicode-xid v0.2.0
  Downloaded smallvec v0.6.10
  Downloaded quick-error v1.2.2
  Downloaded num-integer v0.1.41
  Downloaded ryu v1.0.0
  Downloaded semver v0.9.0
  Downloaded semver-parser v0.7.0
   Compiling proc-macro2 v0.4.30
   Compiling unicode-xid v0.1.0
   Compiling serde v1.0.99
   Compiling libc v0.2.62
   Compiling syn v0.15.44
   Compiling cc v1.0.41
   Compiling ryu v1.0.0
   Compiling semver-parser v0.7.0
   Compiling itoa v0.4.4
   Compiling failure_derive v0.1.5
   Compiling memchr v2.2.1
   Compiling proc-macro2 v1.0.2
   Compiling rustc-demangle v0.1.16
   Compiling autocfg v0.1.6
   Compiling cranelift-entity v0.41.0 (/tmp/cranelift/cranelift-entity)
   Compiling cfg-if v0.1.9
   Compiling log v0.4.8
   Compiling lazy_static v1.4.0
   Compiling unicode-xid v0.2.0
   Compiling quick-error v1.2.2
   Compiling regex-syntax v0.6.12
   Compiling syn v1.0.5
   Compiling bitflags v1.1.0
   Compiling scopeguard v1.0.0
   Compiling plain v0.2.3
   Compiling termcolor v1.0.5
   Compiling smallvec v0.6.10
   Compiling unicode-width v0.1.6
   Compiling indexmap v1.1.0
   Compiling vec_map v0.8.1
   Compiling same-file v1.0.5
   Compiling wasmparser v0.37.1
   Compiling ansi_term v0.11.0
   Compiling strsim v0.8.0
   Compiling semver v0.9.0
   Compiling backtrace-sys v0.1.31
   Compiling cmake v0.1.42
   Compiling capstone-sys v0.10.0
   Compiling num-traits v0.2.8
   Compiling num-integer v0.1.41
   Compiling thread_local v0.3.6
   Compiling humantime v1.2.0
   Compiling cranelift-codegen-meta v0.41.0 (/tmp/cranelift/cranelift-codegen/meta)
   Compiling cranelift-bforest v0.41.0 (/tmp/cranelift/cranelift-bforest)
   Compiling lock_api v0.3.1
   Compiling textwrap v0.11.0
   Compiling walkdir v2.2.9
   Compiling rustc_version v0.2.3
   Compiling wabt-sys v0.6.1
   Compiling quote v0.6.13
   Compiling string-interner v0.7.1
   Compiling atty v0.2.13
   Compiling termios v0.3.1
   Compiling dirs-sys v0.3.4
   Compiling time v0.1.42
   Compiling clicolors-control v1.0.1
   Compiling errno v0.2.4
   Compiling num_cpus v1.10.1
   Compiling memmap v0.7.0
   Compiling serde_json v1.0.40
   Compiling aho-corasick v0.7.6
   Compiling quote v1.0.2
   Compiling scroll v0.9.2
   Compiling parking_lot_core v0.6.2
   Compiling parking_lot v0.9.0
   Compiling cranelift-codegen v0.41.0 (/tmp/cranelift/cranelift-codegen)
   Compiling region v2.1.2
   Compiling clap v2.33.0
   Compiling dirs v2.0.2
   Compiling target-lexicon v0.8.0
   Compiling regex v1.3.1
   Compiling backtrace v0.3.37
   Compiling number_prefix v0.2.8
   Compiling synstructure v0.10.2
   Compiling scroll_derive v0.9.5
   Compiling term v0.6.1
   Compiling env_logger v0.6.2
   Compiling console v0.8.0
   Compiling serde_derive v1.0.99
   Compiling capstone v0.6.0
   Compiling chrono v0.4.9
   Compiling file-per-thread-logger v0.1.2
   Compiling pretty_env_logger v0.3.1
   Compiling goblin v0.0.24
   Compiling failure v0.1.5
   Compiling indicatif v0.11.0
   Compiling wabt v0.9.1
error[E0425]: cannot find value `Armv7` in this scope
 --> /tmp/cranelift/target/debug/build/target-lexicon-3a18bae8002f504e/out/host.rs:3:37
  |
3 |     architecture: Architecture::Arm(Armv7),
  |                                     ^^^^^ not found in this scope
help: possible candidate is found in another module, you can import it into scope
  |
1 | use crate::targets::ArmArchitecture::Armv7;
  |

error[E0425]: cannot find value `Armv7` in this scope
  --> /tmp/cranelift/target/debug/build/target-lexicon-3a18bae8002f504e/out/host.rs:13:27
   |
13 |         Architecture::Arm(Armv7)
   |                           ^^^^^ not found in this scope
help: possible candidate is found in another module, you can import it into scope
   |
1  | use crate::targets::ArmArchitecture::Armv7;
   |

error[E0425]: cannot find value `Armv7` in this scope
  --> /tmp/cranelift/target/debug/build/target-lexicon-3a18bae8002f504e/out/host.rs:49:45
   |
49 |             architecture: Architecture::Arm(Armv7),
   |                                             ^^^^^ not found in this scope
help: possible candidate is found in another module, you can import it into scope
   |
1  | use crate::targets::ArmArchitecture::Armv7;
   |

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0425`.
error: Could not compile `target-lexicon`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

broken by: https://github.com/CraneStation/cranelift/commit/bff2fd221deb1f8fbe4d392a10665ac304144dd7

I'm on rust-1.37.0, in case that it matters.

**Comment by bnjbvr** [comment]
Hi! Thanks for opening an issue. Are you compiling on an ARM device?

**Comment by stefson** [comment]
I do, hence the `-j 2`

(it's an rpi2)

**Comment by bnjbvr** [comment]
target-lexicon is broken; we'll need to upgrade it in Cranelift. Will open an issue there. Thanks for reporting!

**Comment by stefson** [comment]
ah, target-lexikon is part of CraneStation. Thanks for forwarding, can you please 

The error does also show in cross-compile, so you can easily reproduce this via `cargo build --target armv7-unknown-linux-gnueabihf`

Is it https://github.com/CraneStation/target-lexicon/issues/25 ?

**Comment by bnjbvr** [comment]
Yes indeed.

**Comment by stefson** [comment]
when I bump target-lexikon locally to v0.8.1, it's back to live :) 

only one warning, do you want me to open a new issue about it? 

```Compiling cranelift-native v0.41.0 (/tmp/cranelift/cranelift-native)
warning: unused import: `cranelift_codegen::settings::Configurable`
  --> cranelift-native/src/lib.rs:29:5
   |
29 | use cranelift_codegen::settings::Configurable;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: #[warn(unused_imports)] on by default```

**Comment by stefson** [comment]
damit, never meant to close -,-

**Comment by bnjbvr** [comment]
Thanks for confirming it's fixed! We should probably manually bump the version number in all the crates, and remove this use statement. Would you consider opening a pull request to do so, please? :innocent:

**Comment by stefson** [comment]
cd /tmp/ && git clone https://github.com/CraneStation/cranelift.git && cd /tmp/cranelift

grep -r target-lexicon

```
cranelift-wasm/Cargo.toml:target-lexicon = "0.8.0"
cranelift-frontend/Cargo.toml:target-lexicon = "0.8.0"
cranelift-native/Cargo.toml:target-lexicon = "0.8.0"
cranelift-faerie/Cargo.toml:target-lexicon = "0.8.0"
fuzz/Cargo.toml:target-lexicon = "0.8.0"
cranelift-codegen/Cargo.toml:target-lexicon = "0.8.0"
cranelift-reader/Cargo.toml:target-lexicon = "0.8.0"
cranelift-simplejit/Cargo.toml:target-lexicon = "0.8.0"
Cargo.toml:target-lexicon = "0.8.0"
```

Do you mean to change all of these to 0.8.1? This I can do, but I'm not a person who's educated in actually coding c/c++/rust. So removing those use statements (what is that even?), you or someone else must do that.

**Comment by bjorn3** [comment]
> Do you mean to change all of these to 0.8.1?

That would not be necessary. Updating Cargo.lock of users would be enough. You could force it by for example updating the one in `cranelift-codegen/Cargo.toml` as the rest of the crates depend on it.
